[package]
name = "bpls-rs"
version = "0.1.0"
authors = ["CJ Burkey <cjburkey01@gmail.com>"]
edition = "2018"

[dependencies]
bpls-rs-macro = { path = "./bpls-rs-macro" }
bpls-rs-derive = { path = "./bpls-rs-derive" }
