[package]
name = "bpls-rs-derive"
version = "0.1.0"
authors = ["CJ Burkey <cjburkey01@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0.12"
quote = "1.0.4"
syn = {version = "1.0.18", features = ["full"]}

[lib]
proc-macro = true
